- hosts: captain
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Install htop
      apt: name=htop state=latest
    - name: Install nmap
      apt: name=nmap state=latest
    - name: Install OpenJDK 8
      apt: name=openjdk-8-jdk state=latest
      tags: java
    - name: Download JDK 9 Preview
      get_url:
        url: "http://download.java.net/java/jdk9/archive/115/binaries/jdk-9-ea+115_linux-x64_bin.tar.gz"
        validate_certs: no
        checksum: "sha1:82b71db9fcadfc5c3aac5d6d622c28f886c2f5f8"
        dest: "/opt/jdk-9-ea+115_linux-x64_bin.tar.gz"
        headers: "Cookie: oraclelicense=accept-securebackup-cookie"
      tags:
        - optional
        - java
    - name: Install JDK 9 Preview
      unarchive: src=/opt/jdk-9-ea+115_linux-x64_bin.tar.gz dest=/opt copy=no creates=/opt/jdk-9/bin/jshell
      tags:
        - optional
        - java
    - name: Add Gradle repo
      apt_repository: repo='ppa:cwchien/gradle'
      tags:
        - optional
        - java
    - name: Install Gradle
      apt: name=gradle-2.12 state=latest
      tags:
        - optional
        - java
    - name: Install Squid Proxy
      apt: name=squid3 state=latest
    - name: Configure Squid Proxy
      copy: src=files/conf/squid.conf dest=/etc/squid3/squid.conf mode=644 owner=root group=root
      notify: Restart Squid
  handlers:
    - name: Restart Squid
      service: name=squid3 state=restarted
