- hosts: picamera
  become: yes
  become_method: sudo
  gather_facts: no
  vars:
    proxy:
      http_proxy: http://192.168.88.3:3128
      https_proxy: http://192.168.88.3:3128
  tasks:
    - name: Install Java 8 Runtime
      apt: name=openjdk-8-jre state=latest
      environment: "{{proxy}}"
    - name: Install htop
      apt: name=htop state=latest
      environment: "{{proxy}}"
    - name: Install nmap
      apt: name=nmap state=latest
      environment: "{{proxy}}"
    - name: Install Picamera module
      apt: name=python-picamera state=latest
      environment: "{{proxy}}"
    - name: Add camera scripts to PATH
      template: src=files/usr/bin/{{ item }} dest=/usr/bin/{{ item }} mode=755 owner=root group=root
      with_items:
        - eer-camera
        - eer-camera-feed
