- hosts: rasprime
  become: yes
  become_method: sudo
  gather_facts: no
  vars:
    proxy:
      http_proxy: http://192.168.88.3:3128
      https_proxy: http://192.168.88.3:3128
  tasks:
    - name: Download JDK 9 Preview
      get_url:
        url: "http://download.java.net/java/jdk9/archive/115/binaries/jdk-9-ea+115_linux-arm32-vfp-hflt_bin.tar.gz"
        validate_certs: no
        checksum: "sha1:bb663c9841f07e09d405a98e0e1b58e3e60acd6c"
        dest: "/opt/jdk-9-ea+115_linux-arm32-vfp-hflt_bin.tar.gz"
        headers: "Cookie: oraclelicense=accept-securebackup-cookie"
      environment: "{{ proxy }}"
      tags:
        - optional
        - java
    - name: Install JDK 9 Preview
      unarchive: src=/opt/jdk-9-ea+115_linux-arm32-vfp-hflt_bin.tar.gz dest=/opt copy=no creates=/opt/jdk-9/bin/jshell
      tags:
        - optional
        - java
    - name: Install I2C Tools
      apt: name=i2c-tools state=latest
      environment: "{{proxy}}"
    - name: Install htop
      apt: name=htop state=latest
      environment: "{{proxy}}"
    - name: Install Java 8 Runtime
      apt: name=openjdk-8-jre state=latest
      environment: "{{proxy}}"
      tags: java
    - name: Install Python serial module
      apt: name=python-serial state=latest
      environment: "{{proxy}}"
